### ISSUE TITLE
Convert APK Pipeline to GitHub Action

### ISSUE THREAD

**Issue by osterman** [cloudposse/packages#232]
## what
* Preserve the ability to run steps in parallel (as much as possible)
* Build the docker images and use them in subsequent steps (is it possible?)
* Support github PR comments from contributors (or trusted team) to trigger builds on PR comments matching regex (e.g. `/\/ok-to-test/`)

## why
* We have had trouble running builds for Codefresh PRs on forks. 
* Good first project.

**Comment by Nuru** [comment]
@osterman I think we can close this as done now, don't you?

**Comment by osterman** [comment]
Closed in #392
