### ISSUE TITLE
Add tfupdate

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/packages#2615]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) in the `#geodesic` channel or visit our [Slack Archive](https://archive.sweetops.com/geodesic/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Easy updating of module dependencies from inside geodesic

https://github.com/minamijoyo/tfupdate

[`hcledit`](https://github.com/minamijoyo/hcledit) can be used for this but requires more of a strategic approach where `tfupdate` is much more convenient

e.g. with `hcledit`

```
find . -name remote-state.tf > remote-state-files
cat remote-state-files | \
  while read remotestatefile; do \
    hcledit block list --file $remotestatefile | \
      while read block; do \
        echo "hcledit attribute set $block.version '\"0.22.1\"' --file $remotestatefile -u"; \
        echo "hcledit attribute rm $block.stack_config_local_path --file $remotestatefile -u"; \
      done;
  done > update-remotestate.sh
chmod +x update-remotestate.sh
./update-remotestate.sh
```

https://github.com/minamijoyo/tfupdate#module

```
tfupdate module --version "0.23.0" "cloudposse/stack-config/yaml//modules/remote-state" -r .
```

NOTE: for the above update, we'd still require hcledit to remove the `stack_config_local_path` but tdupdate is useful for upgrading module versions across a repository

The formula for this should be similar to the following since the tool is created by the same author.

https://github.com/cloudposse/packages/tree/master/vendor/tfschema
https://github.com/cloudposse/packages/tree/master/vendor/hcledit

**Comment by Nuru** [comment]
Closing as `wontfix` (not going to do it) because there is not enough interest plus, going forward, it is unclear if it contains BSL licensed code.
