### ISSUE TITLE
apk add terraform_0.12@cloudposse cases Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by NamelessHH** [cloudposse/packages#3339]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
in our Dockerfile to build a Geodesic Shell we have a line to add terraform
`RUN apk add terraform_0.12@cloudposse`

this is now giving us an error
```
fetch https://alpine.global.ssl.fastly.net/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch https://alpine.global.ssl.fastly.net/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
fetch https://apk.cloudposse.com/3.11/vendor/x86_64/APKINDEX.tar.gz
fetch https://alpine.global.ssl.fastly.net/alpine/edge/testing/x86_64/APKINDEX.tar.gz
Segmentation fault (core dumped)
```

## Expected Behavior
the line should run terraform

## Steps to Reproduce
1. Add the  [cloudposse package](https://github.com/cloudposse/packages#alpine-repository-recommended)
3. Run 'apk add terraform_0.12@cloudposse'
5. See error

## Screenshots
![image](https://user-images.githubusercontent.com/31907581/220402095-78b67fb6-1ff4-41f8-b704-5067afd8e684.png)

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux Alpine

## Additional Context
We've also tried multiple vbersions of terraform (0.13, 0.14, 0.15) and they all fail with it

**Comment by NamelessHH** [comment]
We found that this was an issue with an older version of alphine in the 0.136.1 version of the shell we were using.  we upgraded to 0.152.5-alpine and everything worked thanks!.

**Comment by osterman** [comment]
@NamelessHH I am glad you figured it out! We recommend everyone move to Debian or CentOS, as a continued investment into Alpine is unlikely.
