### ISSUE TITLE
GitHub Auto Updater Broken

### ISSUE THREAD

**Issue by osterman** [cloudposse/packages#339]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Github Actions to `auto-update` PRs is broken

See: https://github.com/cloudposse/packages/runs/471198424?check_suite_focus=true

**Comment by maximmi** [comment]
should be fixed in #340
