### ISSUE TITLE
404 when downloading Cloudposse public key

### ISSUE THREAD

**Issue by mattmcf** [cloudposse/packages#896]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

Our docker images are failing to build. Our dockerfile includes the following lines from the readme:
```
# Add package repo for chamber
ADD https://apk.cloudposse.com/ops@cloudposse.com.rsa.pub /etc/apk/keys/
RUN echo "@cloudposse https://apk.cloudposse.com/3.11/vendor" >> /etc/apk/repositories
```

I'm see a failure message:
```
Step 4/16 : ADD https://apk.cloudposse.com/ops@cloudposse.com.rsa.pub /etc/apk/keys/
ERROR: Service 'app' failed to build : ADD failed: failed to GET https://apk.cloudposse.com/ops@cloudposse.com.rsa.pub with status 404 Not Found:
```

Normally we'd download the key without issue. Did something expire?

## Steps to Reproduce
2. Run '....'
3. Enter '....'

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux
 - Version [e.g. 10.15]

**Comment by nodiced922** [comment]
Same issue but using 3.9

**Comment by sross07** [comment]
same

**Comment by mattmcf** [comment]
@osterman Can I escalate this to you? We can't build our app without some sort of workaround or solution.

**Comment by Nuru** [comment]
@mattmcf We are investigating.

**Comment by mattmcf** [comment]
@Nuru Thank you!

**Comment by Nuru** [comment]
Fixed. Reopen this issue if you still have problems.

**Comment by mattmcf** [comment]
Thank you @Nuru! I see that this is fixed now.
